# Snakemake will first pull the defined container image, and then create the requested 
# conda environments from within the container. The conda environments will be stored 
# in the working environment. 
# container: "docker://continuumio/miniconda3:4.4.10"
container: "docker://condaforge/mambaforge:latest"

N_NEIGHBORS_LIST = range(1, 11)
METRIC_LIST = ["cityblock", "cosine", "euclidean", "haversine", "l1", "l2", "manhattan", "nan_euclidean"]

# Final output files
rule all:
    input:
        expand("results/n_neighbors={n_neighbors}___metric={metric}.png", n_neighbors=N_NEIGHBORS_LIST, metric=METRIC_LIST)


# Rule to produce the output files for parameter combinations.
rule train_plot:
    resources:
        tmpdir="./tmp"
    input:
        "data/preprocessed/Iris.pkl"
    output:
        "results/n_neighbors={n_neighbors}___metric={metric}.png"
    conda:
        "envs/python.yml" # Rule train_plot will use the conda environment defined in python.yml
    shell:
        "python train_plot.py --n_neighbors {wildcards.n_neighbors} --metric {wildcards.metric}"


# Rule to preprocess the data
rule preprocess:
    resources:
        tmpdir="./tmp"
    input:
        "data/Iris.csv"
    output:
        "data/preprocessed/Iris.pkl"
    conda:
        "envs/python.yml" # Rule train_plot will use the conda environment defined in python.yml
    shell:
        "python preprocess_data.py --input-file {input} --output-file {output}"
 