# Snakemake will first pull the defined container image, and then create the requested 
# conda environments from within the container. The conda environments will be stored 
# in the working environment. 
#container: "docker://continuumio/miniconda3:4.4.10"
#container: "docker://condaforge/mambaforge:latest"
#container: "docker://harbor.cs.aalto.fi/aaltorse-public/coderefinery/parallel-workflow:latest"

N_NEIGHBORS_LIST = range(1, 3)

# Final output files
rule all:
    input:
        expand("results/n_neighbors={n_neighbors}.png", n_neighbors=N_NEIGHBORS_LIST)


# Rule to produce the output files for parameter combinations.
rule train_and_plot:
    input:
        "data/preprocessed/Iris.pkl"
    output:
        "results/n_neighbors={n_neighbors}.png"
    container:
        "docker://harbor.cs.aalto.fi/aaltorse-public/coderefinery/parallel-workflow:latest"
    log: 
        "logs/train_and_plot/n_neighbors={n_neighbors}.log"
    shell:
        "python train_and_plot.py --n_neighbors {wildcards.n_neighbors}" #  1> {log} 2> {log}"


# Rule to preprocess the data
rule preprocess:
    output:
        "data/preprocessed/Iris.pkl"
    container:
        "docker://harbor.cs.aalto.fi/aaltorse-public/coderefinery/parallel-workflow:latest"
    log: 
        "logs/preprocess_data/preprocess.log"
    shell:
        "python preprocess.py" # 1> {log} 2> {log}"
 